apiVersion: v1
kind: Secret
metadata:
  name: my-backstage-secrets
  namespace: backstage-workshop
type: Opaque
data:
  GITHUB_TOKEN: <YOUR GITHUB TOKEN>
  BACKEND_SECRET: <BACKEND SECRET> # Execute in the terminal node -p 'require("crypto").randomBytes(24).toString("base64")'
